### PR TITLE
add test-base image dockerfile

### PR DESCRIPTION
**Pull request by mjudeikis**
Adds test-base image dockerfile so we can build using ci-operator and not BC.

### CODE REVIEW

**Comment by kargakis** [comment]
Is it different from the test-base image we keep in openshift/release? Why not use that?

**Comment by kargakis** [comment]
Also I think we build already using the ci-operator, no?

**Comment by mjudeikis** [comment]
we build using build config. And now I need to add some borrowed logic from openshift-ansible so we can run commands as non priv containers and use ssh.

**Comment by mjudeikis** [comment]
> Also I think we build already using the ci-operator, no?

To build using ci-operator code has to sit outside release repository. This is not a case for this one.

**Pull request closed without merging**
