### PR TITLE
added Web Console Latency in milliseconds graph

### PR DESCRIPTION
**Pull request by thanasisk**

### CODE REVIEW

**Comment by thanasisk** [comment]
@charlesakalugwu can you please confirm the version you are looking at? FYC I added the WiP label while you are reviewing

**Comment by charlesakalugwu** [comment]
oh sorry about that! i erroneously performed my test using the dashboard json from #86. I just tested #86 and this separately and everything is fine.

**Comment by jim-minter** [comment]
dashboard format in the git repo changed in #93 - should start ```
{
  "dashboard": {
```

**Comment by charlesakalugwu** [comment]
> dashboard format in the git repo changed in #93 - should start
> 
> ```
> {
>   "dashboard": {
> ```
> and then there are a few new fields at the end as well.

Ah right..I remember this from the past....this is needed when provisioning grafana dashboards over its REST api. We'll need to develop some tools to help us test these changes more easily.

**Comment by jim-minter** [comment]
closing for #106

**Pull request closed without merging**
