### PR TITLE
add basic log viewer SRE application

### PR DESCRIPTION
**Pull request by jim-minter**
@openshift/sig-azure this is a starting point for discussion - there are multiple necessary/potential improvements including
- Dockerfile
- kubernetes resources to deploy onto SRE cluster, including openshift-oauth front
- pkg/clusters implementation for production
- reuse of pkg/clusters with prometheus-sidecar
- audit log
- UI improvements, e.g. example queries, list of available fields

### CODE REVIEW

**Comment by mjudeikis** [comment]
@jim-minter  thanks a lot for this!!!! This is what I needed to jump-start this work. I had a very small understanding on how this can be done, but this gives a super good start!

**Comment by pweil-** [comment]
> * Would adding user authentication to view the logs be something for future? (obviously not when used locally)

needs to be behind oauth proxy with SAR

**Comment by mjudeikis** [comment]
> needs to be behind oauth proxy with SAR 

I want to pick this as separate PR

**Pull request merged**
