### PR TITLE
refactor yaml files locations

### PR DESCRIPTION
**Pull request by mjudeikis**
Move yaml around to converged structure
Add limits to pods so we would try to avoid OOM. Will need to test those as we go.

### CODE REVIEW

**Comment by jim-minter** [comment]
@mjudeikis I'm confused by this - I tried to rebase it locally but it looks like much of this change already went in as part of #84?  That rather implies that #84 did more than it said on the can, which isn't great practice?

**Comment by mjudeikis** [comment]
> That rather implies that #84 did more than it said on the can, which isn't great practice?

Yes, I was working on these things in parallel and I just got confused with commits :/ by bad. And we need to do better reviews on this too :/

**Comment by mjudeikis** [comment]
@jim-minter repurposed PR to change makefile and use what's already there and committed :/

**Comment by jim-minter** [comment]
/hold

@mjudeikis please don't merge this - merge #93.  We can discuss what of this also needs adding after that.

**Comment by kargakis** [comment]
reopen if still relevant

**Pull request closed without merging**
