### PR TITLE
add readme

### PR DESCRIPTION
**Pull request by mjudeikis**
add some docs about our grafana, prometheus arch and life

### CODE REVIEW

**Comment by mjudeikis** [comment]
ping @openshift/sig-azure

**Comment by jim-minter** [comment]
@mjudeikis bump - please rebase

**Comment by jim-minter** [comment]
@mjudeikis this is still touching sre/grafana-deployment/openshift/PersistentVolumeClaim/grafana.yaml and presumably shouldn't be?

**Comment by mjudeikis** [comment]
sorted.

**Pull request merged**
